// Generated by gencpp from file drrobot_X80_player/CustomSensor.msg
// DO NOT EDIT!


#ifndef DRROBOT_X80_PLAYER_MESSAGE_CUSTOMSENSOR_H
#define DRROBOT_X80_PLAYER_MESSAGE_CUSTOMSENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drrobot_X80_player
{
template <class ContainerAllocator>
struct CustomSensor_
{
  typedef CustomSensor_<ContainerAllocator> Type;

  CustomSensor_()
    : header()
    , robot_type()
    , customADData()
    , customIO(0)  {
    }
  CustomSensor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_type(_alloc)
    , customADData(_alloc)
    , customIO(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_type_type;
  _robot_type_type robot_type;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _customADData_type;
  _customADData_type customADData;

   typedef uint8_t _customIO_type;
  _customIO_type customIO;





  typedef boost::shared_ptr< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> const> ConstPtr;

}; // struct CustomSensor_

typedef ::drrobot_X80_player::CustomSensor_<std::allocator<void> > CustomSensor;

typedef boost::shared_ptr< ::drrobot_X80_player::CustomSensor > CustomSensorPtr;
typedef boost::shared_ptr< ::drrobot_X80_player::CustomSensor const> CustomSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drrobot_X80_player::CustomSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drrobot_X80_player

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'drrobot_X80_player': ['/home/emmo/catkin_ws/src/drrobot_X80_player/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99688dde61b19bf7f23d2791779ffdd3";
  }

  static const char* value(const ::drrobot_X80_player::CustomSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99688dde61b19bf7ULL;
  static const uint64_t static_value2 = 0xf23d2791779ffdd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drrobot_X80_player/CustomSensor";
  }

  static const char* value(const ::drrobot_X80_player::CustomSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# custom Sensor information message from DrRobot Robot.\n\
\n\
Header header    	# timestamp in the header is the time the driver\n\
		 	# returned the battery/power reading\n\
string robot_type	# robot type, I90 series, sentinel3 or Hawk/H20 Power/Motion\n\
\n\
#make sure what sensor is on your expanded sensor port\n\
uint32[] customADData		# custom AD channel 8 channel on the board, which channel is avaiable please contact Dr Robot\n\
uint8 customIO    #expanded IO\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drrobot_X80_player::CustomSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_type);
      stream.next(m.customADData);
      stream.next(m.customIO);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drrobot_X80_player::CustomSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drrobot_X80_player::CustomSensor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_type);
    s << indent << "customADData[]" << std::endl;
    for (size_t i = 0; i < v.customADData.size(); ++i)
    {
      s << indent << "  customADData[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.customADData[i]);
    }
    s << indent << "customIO: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.customIO);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRROBOT_X80_PLAYER_MESSAGE_CUSTOMSENSOR_H
