// Generated by gencpp from file drrobot_X80_player/MotorInfo.msg
// DO NOT EDIT!


#ifndef DRROBOT_X80_PLAYER_MESSAGE_MOTORINFO_H
#define DRROBOT_X80_PLAYER_MESSAGE_MOTORINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drrobot_X80_player
{
template <class ContainerAllocator>
struct MotorInfo_
{
  typedef MotorInfo_<ContainerAllocator> Type;

  MotorInfo_()
    : header()
    , robot_type()
    , encoder_pos(0)
    , encoder_vel(0)
    , encoder_dir(0)
    , motor_current(0.0)
    , motor_pwm(0)  {
    }
  MotorInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_type(_alloc)
    , encoder_pos(0)
    , encoder_vel(0)
    , encoder_dir(0)
    , motor_current(0.0)
    , motor_pwm(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_type_type;
  _robot_type_type robot_type;

   typedef uint32_t _encoder_pos_type;
  _encoder_pos_type encoder_pos;

   typedef uint32_t _encoder_vel_type;
  _encoder_vel_type encoder_vel;

   typedef uint32_t _encoder_dir_type;
  _encoder_dir_type encoder_dir;

   typedef float _motor_current_type;
  _motor_current_type motor_current;

   typedef uint32_t _motor_pwm_type;
  _motor_pwm_type motor_pwm;





  typedef boost::shared_ptr< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MotorInfo_

typedef ::drrobot_X80_player::MotorInfo_<std::allocator<void> > MotorInfo;

typedef boost::shared_ptr< ::drrobot_X80_player::MotorInfo > MotorInfoPtr;
typedef boost::shared_ptr< ::drrobot_X80_player::MotorInfo const> MotorInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drrobot_X80_player::MotorInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drrobot_X80_player

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'drrobot_X80_player': ['/home/emmo/catkin_ws/src/drrobot_X80_player/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e31f4f22948e8b2ee140c8cc701e042";
  }

  static const char* value(const ::drrobot_X80_player::MotorInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e31f4f22948e8b2ULL;
  static const uint64_t static_value2 = 0xee140c8cc701e042ULL;
};

template<class ContainerAllocator>
struct DataType< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drrobot_X80_player/MotorInfo";
  }

  static const char* value(const ::drrobot_X80_player::MotorInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# motor sensor data message from DrRobot Robot.\n\
\n\
Header header    	# timestamp in the header is the time the driver\n\
		 	# returned the battery/power reading\n\
string robot_type	# robot type, I90 series, sentinel3 or Jaguar Power/Motion\n\
\n\
uint32 encoder_pos	# encoder positon count\n\
uint32 encoder_vel	# encoder velocity value\n\
uint32 encoder_dir	# encoder direction\n\
\n\
float32 motor_current	# motor current\n\
uint32 motor_pwm	# output PWM value, only for Jaguar series robot\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drrobot_X80_player::MotorInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_type);
      stream.next(m.encoder_pos);
      stream.next(m.encoder_vel);
      stream.next(m.encoder_dir);
      stream.next(m.motor_current);
      stream.next(m.motor_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drrobot_X80_player::MotorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drrobot_X80_player::MotorInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_type);
    s << indent << "encoder_pos: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encoder_pos);
    s << indent << "encoder_vel: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encoder_vel);
    s << indent << "encoder_dir: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encoder_dir);
    s << indent << "motor_current: ";
    Printer<float>::stream(s, indent + "  ", v.motor_current);
    s << indent << "motor_pwm: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.motor_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRROBOT_X80_PLAYER_MESSAGE_MOTORINFO_H
